import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/StyledComponentsRegistry";
import { Providers } from "@/lib/Providers";
import { AppLayout } from "@/components/layout/AppLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <html>
          <body>
            <StyledComponentsRegistry>
              <Providers>
                <AppLayout>{children}</AppLayout>
              </Providers>
            </StyledComponentsRegistry>
          </body>
        </html>
      </body>
    </html>
  );
}
